version: '3'

services:
  jekyll-serve:
    image: website-src:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/src
    ports:
      - '4000:4000'
      - '35729:35729'